### ISSUE TITLE
Maptool 

### ISSUE THREAD

**Issue by munirfarzeen** [tier4/AutowareArchitectureProposal.proj#200]
Hi, 
I am using an online maptool to make lanelet vector map of my univeristy. 
i have a PCD 3D map of the university. When I draw the lanelet using the tool. I get the error that "next lanelet is empty"
As shown in the image. can you help me in this regard @esteve @shinpei0208 
thank you 
![image](https://user-images.githubusercontent.com/23066497/116835858-40605f80-abff-11eb-9d27-4ec32608cc1c.png)

**Comment by ghost** [comment]
@likui01 Hello there! I work at Tier IV and I can try and help out with this issue. Is the following a correct statement of the steps that you took?
1. Loaded an existing PCD map into the Vector Map Builder
2. Created a Lanelet2 vector map
3. Tried adding a Lanelet and then the "next lanelet is empty" error occurred

Does this happen whenever and wherever on the map you try to add a Lanelet? Would you be able to share your PCD map data with me so that I can take a closer look to try to figure out the problem?

**Comment by munirfarzeen** [comment]
@LalithVipulananthan  thank you for your response. 
yes I have followed the same 3 steps as you mentioned and get the same error. 
attach is a segment of my PCD map. 
https://drive.google.com/file/d/1egpRQhuJgkZrgDN879cug4b2fqlxI8Ci/view?usp=sharing

**Comment by ghost** [comment]
@likui01 From what I have been able to determine, the "error" is actually just a warning to indicate that the new Lanelet is not connected to another one in front of it (in the direction of travel).  Since this is a warning, there should be no issues with exporting your Lanelet2 vector map from the Vector Map Builder application, nor with using the exported Lanelet2 vector map with Autoware. Please continue with creating your vector map and let us know if any further issues are experienced.

Please note that if you see a number greater than 0 next to "Problem" in the top right of the window, this indicates that there are genuine errors/problems within the vector map and you will not be able to export your map until these have been resolved.

![image](https://user-images.githubusercontent.com/63835446/117764640-cd429300-b267-11eb-9236-98a8a7139bb3.png)

**Comment by munirfarzeen** [comment]
@LalithVipulananthan 
Thank you for your response. 
I want to ask, how can I make a lane with dash lane marking. 
I used the centerline tool to create dash lane marking as shown in the figure below.
![image](https://user-images.githubusercontent.com/23066497/118429591-fd2ce300-b70c-11eb-8fe6-ede9c614a265.png)
But when I used it with autoware, the autoware took the centerline as waypoints and car travel on them.
![image](https://user-images.githubusercontent.com/23066497/118429664-25b4dd00-b70d-11eb-8856-4989bb384afe.png)
How can make multi lane? 
thank you

**Comment by ghost** [comment]
@likui01 Apologies for not replying sooner. I answered your first question as a courtesy, but as it seems that you have additional questions that are unrelated to the AutowareArchitectureProposal repository, I think it would be better to ask this question (and any others that you may have) on the [ROS Answers site](https://answers.ros.org/questions/). Thank you for using our Vector Map Builder product, and I hope that your issue can be resolved quickly.
